### ISSUE TITLE
Image Viewer destroys transparency when importing images

### ISSUE THREAD

**Issue by Vladabdf** [Xeeynamo/OpenKh#330] opened 2020-12-20 20:53 UTC
Alpha gets replaced with solid black with the Image Viewer. ImgTool is unaffected. (Found by @Topaz-Reality). This issue is suspected to date back at least to #305, but it may go even further.
This isn't the first time alpha has been broken, so to make it easier to detect in the future, I'm also requesting that the image viewer finally get the option to display alpha properly, with the option to display a user selected solid color.

**Comment by Topaz-Reality** [comment] 2020-12-20 20:56
The size of the file also doubles, as mentioned in #276
While the negative issue seems to be addressed, the other issues remain.

**Comment by Vladabdf** [comment] 2020-12-20 20:57
Regarding the size doubling, I'm convinced that's the image viewer assuming you want the image you're importing as 32bpp, which will obviously bloat the size. Checking "Convert to 8bpp image" should fix that issue, but the alpha may still be broken.

**Comment by Topaz-Reality** [comment] 2020-12-20 20:58
Perhaps a check on color count would be the best, then? Because even though I had "use pngquant" checked and used pngquant separately, the size still doubled.

**Comment by Vladabdf** [comment] 2020-12-20 21:03
Pngquant != 8bpp conversion. They're different settings. Pngquant supports any color ammounts from 1 ~ 256, but the tool has explicit options for 4bpp (16 color) or 8bpp (256 colors), of which both are naturally supported by KH2 + nQuant (the default quantization tool). Because of this, pngquant setting will never affect your file size, as the amount of data is still the same whether you use it or not. Bit depth is the key problem here for sure.

**Comment by Topaz-Reality** [comment] 2020-12-20 21:07
I mean, even if the image is 32bpp you can still check if it has less than or equal to 256 or 16 colors, that could serve to make this tool a bit smarter in nature.

**Comment by Xeeynamo** [comment] 2020-12-21 21:23
Would you mind to check if #332 fixes it?

**Comment by Vladabdf** [comment] 2020-12-21 22:55
I can confirm #332 fixes the alpha destruction, but there is a swizzling error. (Look at the "munnies" and "time" text at the bottom left.)
![image](https://user-images.githubusercontent.com/20749232/102829704-b03f1d80-43b5-11eb-910e-c88c151112ac.png)

**Comment by Topaz-Reality** [comment] 2020-12-21 23:00
It still has alpha destruction from what I can tell. Notice the bars in the image Vladabdf posted have incorrect alpha at the unhighlighted elements.
Here is an image for reference:
![image](https://user-images.githubusercontent.com/28973970/102829984-5eb88200-43f9-11eb-8482-e8cf79c4a538.png)

**Comment by Xeeynamo** [comment] 2020-12-21 23:06
> I can confirm #332 fixes the alpha destruction, but there is a swizzling error. (Look at the "munnies" and "time" text at the bottom left.) ~Additionally, some colors appear to be inaccurate and almost as if alpha is still being messed up, but not completely omitted.~
> I was responsible for the color destruction I believe. Only the swizzling error remains.
> ![image](https://user-images.githubusercontent.com/20749232/102829704-b03f1d80-43b5-11eb-910e-c88c151112ac.png)

Does the code on `master` (so not #332) have the swizzling error? Just checking because it's weird it is now present after merging #329 . Just checking if this is a separate issue.

**Comment by Vladabdf** [comment] 2020-12-21 23:07
I found out what was causing the swizzling error. I imported an image used from the previously broken version of the viewer which did have the error, so that was entirely my fault. #332 has no errors, produces the desired result, and works as intended. Sorry for the confusion!

**Comment by Xeeynamo** [comment] 2020-12-24 16:25
I am closing as it seems that the issue is fixed.

**Closed by Xeeynamo** 2020-12-24 16:25 UTC
Labels: bug, duplicate
