### ISSUE TITLE
Image Viewer distorts imported image after saving.

### ISSUE THREAD

**Issue by DiamondHuntet** [Xeeynamo/OpenKh#276] opened 2020-11-12 06:28 UTC
When importing a png into an IMZ, the image viewer properly shows the imported image. After saving, the image still appears as it should. When reopening the IMZ or patching the image into the game, however, the image is photo negative and has substantial quality loss. It also drastically increases in file size.
After importing:
![before](https://user-images.githubusercontent.com/19317369/98903338-62192f00-2485-11eb-9f87-a94c67dd4e2e.png)
After saving (and reopening the IMZ):
![after](https://user-images.githubusercontent.com/19317369/98903337-61809880-2485-11eb-8f4f-9064102f125d.png)

Size difference:
![size before](https://user-images.githubusercontent.com/19317369/98903862-6560ea80-2486-11eb-8496-6c918cd6a9e1.png)
![size after](https://user-images.githubusercontent.com/19317369/98903863-65f98100-2486-11eb-9ac7-bb517dfd314d.png)

**Comment by Vladabdf** [comment] 2020-11-12 06:58
While not exactly a duplicate of #223, the issues are both relevant to each other. This should be fixed quickly if possible. For now however, the solution is to generate IMGZ files with the command line tool `OpenKh.Command.ImgTool` instead. I have used it reliably with zero issues for a while now.

**Comment by DiamondHuntet** [comment] 2020-11-12 08:14
A workaround I've found is to select "Convert to 8-bpp image" before saving. I think the issue may be the rgba8888 format the png is imported as

**Comment by kenjiuno** [comment] 2020-11-12 14:40
Thanks for using and reporting!

Currently the file size increase problem is brought by technical difficulty.
GDI+ component loads 4bpp/8bpp png image as 32bpp (Rgba8888).
8bpp → 32bpp : file size x4 times.

> A workaround I've found is to select "Convert to 8-bpp image" before saving. I think the issue may be the rgba8888 format the png is imported as

Yes, this workaround is valid way for now (although this behavior is undocumented).

I will check channel swapping problem of Blue and Red, as you have reported, and it is bug.

**Comment by kenjiuno** [comment] 2020-11-12 15:27
> I will check channel swapping problem of Blue and Red, as you have reported, and it is bug.

Sorry I misunderstood. This channel swapping issue seems to be fixed by merging #254

**Comment by Xeeynamo** [comment] 2020-12-01 17:59
@DiamondHuntet can you check if the issue has been fixed in the latest release? If yes, I plan to close this issue. If not, we still need to look at it.

**Comment by Vladabdf** [comment] 2020-12-21 23:19
Color swap fixed as of #254, swizzling/quality loss fixed as of #329. I'll go ahead and close this and will document the 8bpp -> 32bpp conversion workaround in our tool documentation so any future users do not experience that issue as well.

**Closed by Vladabdf** 2020-12-21 23:19 UTC
Labels: bug
