### ISSUE TITLE
MapStudio Crash

### ISSUE THREAD

**Issue by 1234567890num** [Xeeynamo/OpenKh#342] opened 2020-12-29 14:48 UTC
MapStudio crashes when trying to open b_00 spawn point in eh06 (Nothing's Call)

**Comment by Topaz-Reality** [comment] 2020-12-30 02:22
Could you provide the error messages that pop up (if any) and some screenshots to help the devs understand the issue?
Thanks a ton for the issue.

**Comment by 1234567890num** [comment] 2020-12-30 06:34
There's no error messages before the crash. In the scenario presented in the screenshot the progam will crash immediately upon clicking.

![crash](https://user-images.githubusercontent.com/53823593/103334268-4d2f4400-4aa3-11eb-9d0d-a6f7aee6e893.png)

**Comment by Xeeynamo** [comment] 2020-12-30 10:47
It seems to be caused by `obj\M_EX870.mdlx` as MapStudio (`ObjEntryController.cs:74`) always expect a texture. The 3D model is a white pyramid and it looks like to be unused in the final game too.

**Comment by Vladabdf** [comment] 2021-01-04 00:16
Fixed with #350.

**Closed by Vladabdf** 2021-01-04 00:16 UTC
